import {InfoAccountLogin} from './InfoAccountLogin'
import {InfoForgetPassword} from './InfoForgetPassword'
import {InputForm} from './InputForm'
import {SubmitButton} from './SubmitButton'
import { InfoAccountRegister } from './InfoAccountRegister'
import { Loader } from './Loader'
import { InfoAlert } from './InfoAlert'
import { CircleInfo } from './CircleInfo'
import { ForwardPageButton } from './ForwardPageButton'
export {InfoAccountLogin , InfoForgetPassword , InputForm , SubmitButton, InfoAccountRegister , Loader , InfoAlert , CircleInfo , ForwardPageButton}
